### ISSUE TITLE
Kermits Peer-to-peer Code Review

### ISSUE THREAD

**Issue by Joseph-Burke** [defoebrand/HTML-CSS-Capstone-Project#2]
Great job, responsive, looks good.
Logo in the footer is currently exceeding the page at 320px.
Fix carousel cards; currently, the bigger cards are expanding the height of the carousel and the smaller cards are contracting it.
Some extra padding could be used on the sections where it's a bit thin between the container edge and the cards.
Replace Lorem Ipsum with realistic content in the footer.
Banner link on hover colors should be more legible/contrasted.
Social icon need resizing slightly.
Footer categories are exceeding the footer/html at 320px screen width. Possible solution is just hiding them for Mobile S viewers.

Super nice project, good luck!

**Comment by defoebrand** [comment]
All issues addressed
